Fix ReSpec errors
w3c/screen-orientation pull request #122
Opened 2018-10-12 13:10 UTC by Johanna-hub

ReSpec is showing two warnings:
- Remove '!' from the start of the reference [[!PAGE-VISIBILITY]].
- Broken local reference found in document in three places (all from `#widl-Screen-Orientation.`)

For the second, I have manually added in a corresponding id as stated in the ReSpec docs, since ReSpec has automatically generated these`#widl` identifiers.

2018-10-12 13:29 UTC, marcoscaceres requested changes
Just a small change. I’ll send you an example of how to fix the id issue on Monday.

2018-10-12 13:29 UTC, marcoscaceres commented on index.html
>          <h2>
Let’s remove this one for now. I’ll show you a different way to fix this (we want ReSpec to manage the IDs).

2018-10-13 08:21 UTC, Johanna-hub commented on index.html
>          <h2>
Thanks for quick review and I'll amend Monday 🙂

2018-10-16 09:29 UTC, marcoscaceres commented on index.html
> +                <var>doc</var> 's <a><code>screen.orientation</code></a>object.
nit: can you please fix the space between that </var> and `'s`

2018-10-16 10:39 UTC, marcoscaceres approved these changes
👍

2018-10-16 10:39 UTC, marcoscaceres commented
Marked as non substantive for IPR from ash-nazg.

2018-10-17 02:48 UTC, merged