Editorial: Edits to Interface Definitions
w3c/screen-orientation pull request #130
Opened 2019-01-08 11:15 UTC by Johanna-hub

- Removed the 

> 3. Interface Definitions

 heading as unnecessary
- Changed `orientation` object to attribute with own subheading
- Added `unlock`, `lock` method subheadings and `type`, `angle` and `onchange` attribute subheadings

(In 3.1 I can't get `orientation` in the text to link to the heading and getting ReSpec warning, advice welcome!)

2019-01-08 13:36 UTC, marcoscaceres requested changes
Couple of little suggestions and markup fixes...

2019-01-08 13:36 UTC, marcoscaceres commented on index.html
> +      defines a <code>Screen</code> interface, which this specification
I think here we should to formally define and link to `Screen`. 

```suggestion
      defines the <code><dfn data-cite="CSSOM-View#screen">Screen</dfn></code> interface, which this specification
```

2019-01-08 13:36 UTC, marcoscaceres commented on index.html
> +      </h2>The <a data-cite="CSSOM-View">CSSOM View Module</a> specification
Note missing paragraph (will need a tidy after, and a closing `<p>`): 
```suggestion
      </h2><p>The <a data-cite="CSSOM-View">CSSOM View Module</a> specification
```

2019-01-08 13:36 UTC, marcoscaceres commented on index.html
> +          <dfn data-dfn-for='Screen'>orientation</dfn> attribute
I'd suggest moving `data-dfn-for='Screen'` up to the `<section>` tag on line 152. That way, it's clear that the whole section is defining 'Screen''s things (even though there is only one attribute).

2019-01-08 13:36 UTC, marcoscaceres commented on index.html
> +          <a>ScreenOrientation</a>, which is described below.
Probably ok to drop the "which is described below", as it's hyperlinked. 

```suggestion
          <a>ScreenOrientation</a>.
```

2019-01-09 02:28 UTC, marcoscaceres commented on index.html
> +        The term <a>screen</a> is equivalent to the screen of the output device
Ah! we need to be careful here, because "screen" is being used as a concept (not referring to the `Screen` Interface). So we might need a different definition for it if that's true.

If screen does get used as a concept, I think you can define it as follows:

```HTML
<dfn data-lt="screen concept" data-lt-noDefault>screen</dfn>
```

And then reference screen (when not describing the Web IDL interface):

```HTML
<a data-lt="screen concept">screen</a>
```

Hopefully that makes sense!

2019-01-09 09:27 UTC, Johanna-hub commented on index.html
> +        The term <a>screen</a> is equivalent to the screen of the output device
Thanks!  I have defined the screen concept as suggested, I can't seem to actually find any references that aren't to the Web IDL interface, but will keep an eye out when I am editing the other sections and going over again and put in the reference if needed.

2019-01-09 10:09 UTC, marcoscaceres approved these changes
Looking good.

2019-01-09 10:25 UTC, merged