Editorial: Examples section edits
w3c/screen-orientation pull request #137
Opened 2019-01-23 22:30 UTC by Johanna-hub

In testing Example 1 with the discussed revisions, I came across some issues so a lot of it has been rewritten, so please give feedback!

- we changed document.documentElement.requestFullScreen() to document.body.requestFullScreen() for reasons of length.  This actually makes the whole screen go black so I've changed it back to solve that problem
- The way I had written the example before, the button text only changed when it was pressed.  I have now changed it so that it also changes on user rotation (otherwise user could rotate manually to portrait and it would still say lock to portrait).  It also displays the opposite orientation on load.

Other example edits have been completed, sections/titles, edits and moving it up to Introduction section.

***
<a href="https://pr-preview.s3.amazonaws.com/Johanna-hub/screen-orientation/pull/137.html" title="Last updated on Jan 29, 2019, 11:34 AM UTC (e833f95)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/screen-orientation/137/98b4058...Johanna-hub:e833f95.html" title="Last updated on Jan 29, 2019, 11:34 AM UTC (e833f95)">Diff</a>

2019-01-24 04:12 UTC, marcoscaceres requested changes
Looking good, but example 1 needs a bit of a rework...

2019-01-24 04:12 UTC, marcoscaceres commented on index.html
> +    if (type.startsWith("portrait")) {
Nit: maybe just... 
```JS
return type.startsWith("portrait") ? "landscape" : "portrait";
```

2019-01-24 04:12 UTC, marcoscaceres commented on index.html
> +  &lt;button onclick="rotate() id="lockBtn"&gt;
If we pass "this", then we don't need to look up the button. 
```suggestion
  &lt;button onclick="rotate(this)"&gt;
```

2019-01-24 04:12 UTC, marcoscaceres commented on index.html
> +  async function rotate() {
See below... we can just pass the button that was clicked.  
```suggestion
  async function rotate(rotateBtn) {
```

2019-01-24 04:12 UTC, marcoscaceres commented on index.html
> +    const rotateBtn = document.getElementById("rotateBtn");
See below... 
```suggestion

```

2019-01-24 04:12 UTC, marcoscaceres commented on index.html
> +  screen.orientation.addEventListener("change", show);
combine these two into a singe
```JS
addEventListener("change", ()=>{
   show();
   btnOrientation(); 
}) 
```
That also assures the order means that the browser doesn't need to fire two separate events.

2019-01-24 04:12 UTC, marcoscaceres commented on index.html
> +  function btnOrientation() {
Nit - make sure every functions name is a verb (and clearly indicates what action it does), and not a noun. Also, it's always best to pass things into a function, and not rely on the global scope. 
  
```suggestion
  function updateDetails(lockButton) {
```

2019-01-24 04:12 UTC, marcoscaceres commented on index.html
> +  function oppOrientation() {
As above with the name... maybe `getOppositeOrientation`. Generally, try to avoid abbreviations in names (applies globally as a comment).

2019-01-24 04:12 UTC, marcoscaceres commented on index.html
> +  const lockButton = document.getElementById("lockBtn");
This will be "racy" because lockButton doesn't actually exist yet (the HTML parser has not yet parsed button underneath). So this will be null.  

I'd suggest deleting it, and query the doc only when you need this. 

```suggestion

```

2019-01-24 04:12 UTC, marcoscaceres commented on index.html
> +    lockButton.textContent = `Lock to ${btnOrientation}`;
I think this is not correct. As we discussed yesterday, `.unlock()` doesn't mean it will revert the orientation. Thus, the `lockButton`'s text should always just be "Unlock". However, the "Rotate" button should change its text...

2019-01-24 10:40 UTC, Johanna-hub commented
I have incorporated the changes and tested again on my phone.  

I had to leave an id on the button because we need to change the text on the button on load and on manual rotation, so can't just rely on the click.  I only look up the id on the associated event listeners.

2019-01-29 04:06 UTC, marcoscaceres approved these changes
I think there might still be a tiny bug in the button. See suggestion. The other examples seem fine.

I think we should let Example 1 "cook" 🥘 for a bit... I'm still seeing places were we could make a few tweaks. I'd like to come back and revise it a bit later in the internship. However, we got more fun/pressing things to focus on :)

2019-01-29 04:06 UTC, marcoscaceres commented on index.html
> +  &lt;button onclick="rotate() id="button"&gt;
Note that this was still buggy... missing closing quote and we should pass in this.  

```suggestion
  &lt;button onclick="rotate(this)" id="button"&gt;
```

2019-01-29 11:35 UTC, Johanna-hub commented
> I think we should let Example 1 "cook" 🥘 for a bit... I'm still seeing places were we could make a few tweaks. I'd like to come back and revise it a bit later in the internship. However, we got more fun/pressing things to focus on :)

Is it ok to merge now and work on Example 1 later or should we wait?

2019-01-29 11:50 UTC, marcoscaceres commented
Totally fine to merge!

2019-01-29 11:51 UTC, merged